spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/localhost
    username: root
    password: ""  # Leave this empty since there's no password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
